name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

     # - name: Build
      #  run: npm run build

      - name: Zip Code
        run: |
          # Create a directory to hold the zip file
          mkdir zipped_code
          
          # Zip the entire codebase (excluding .git directory)
          zip -r zipped_code/code.zip . -x ".git/*"
