name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    #strategy:
     # matrix:
      #  node-version: [ 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      #- name: Set up Node.js
      # uses: actions/setup-node@v2
       # with:
        #  node-version: ${{ matrix.node-version }}
      
     # - name: Build
      #  run: npm run build

      - name: Zip Code
        shell: bash
        run: |
          mkdir zipped_code
          zip -r zipped_code/code.zip . -x "*.git*"

    
      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your desired AWS region

      - name: Transfer Zip to S3
        run: aws s3 cp zipped_code/code.zip s3://githubnodetest/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install EB CLI
        run: |
          pip install awsebcli

      - name: Initialize EB CLI
        run: eb init Githubcode-env --platform "Node.js" --region us-east-1  # Replace with your application name and region

      - name: Deploy to Elastic Beanstalk
        run: eb deploy Githubcode-env --staged
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  
